#!/bin/bash

# Use bashutils to run etest
# @requires bashutils environment variable BASHUTILS_HOME to be set to where bashutils is installed.
# This can be done in .bashrc. Example BASHUTILS_HOME=/home/myuser/bashutils
# I am just going to set it here

BASHUTILS_HOME=${HOME}/bashutils

BASHUTILS=${BASHUTILS_HOME}/share

if [[ ! -e ${HOME}/bash_programs/up/test/test_logs ]]; then
    mkdir ${HOME}/bash_programs/up/test/test_logs
fi

${BASHUTILS_HOME}/bin/etest --verbose --log_dir ${HOME}/bash_programs/up/test/test_logs ${HOME}/bash_programs/up/test/up.etest
